CREATE TABLE IF NOT EXISTS car (
   id SERIAL NOT NULL,
   manufacturer VARCHAR(100) NOT NULL,
   model VARCHAR(100) NOT NULL,
   color VARCHAR(50) NOT NULL,
   engine VARCHAR(50) NOT NULL,
   chassis VARCHAR(50) NOT NULL,
   date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   date_updated TIMESTAMP NULL,
   CONSTRAINT id_pkey PRIMARY KEY (id)
);